- src/junit/BooleanTest.java
A basic example on how to create a unit test with JUnit.
> feat JUnit test example #24

- src/junit/LIC_test.java
- src/main/CMV.java
Made the function public, if private is prefered a get function for the field could be implemented.
> Feature: Added tests to lic5 /Issue #19

- src/junit/Helper_Function_Test.java
- src/main/Helper_Functions.java
Added some helper functions for use in the LICs, one that calculates the angle between three points where two are the rays and one is the vertex, as well as some other vector calculation ease of life functions, see separate commits.
All tests for each function pass
> Adding helper functions, closes #49

- src/junit/LIC_test.java
- src/main/CMV.java
Tests included, which were kind of a pain to write and I'm not 100% satisfied that they're testing everything but it'll do
> Lic9, closes #14

- src/junit/LIC_test.java
- src/main/CMV.java
> Fix: Changed to private and utilized get function /Issue #19

- src/junit/Helper_Function_Test.java
- src/main/Helper_Functions.java
Added a function calculating the area of a triangle given its three vertices as input. A simple test shows that it works correctly.
> feat: triangle area helper, closes #65

- src/junit/LIC_test.java
- src/main/CMV.java
Fixed a bug in lic3, also changed so that it uses the trinagle area helper function and also added a test for it because I realized it didn't have one
> fix+feat: changed lic3 + added test closes #67

- src/junit/Helper_Function_Test.java
- src/junit/LIC_test.java
- src/main/CMV.java
- src/main/Helper_Functions.java
I think we have to merge the triangle helper function in PR #66 first to avoid conflicts
> implement Lic 10, closes  #12

- src/junit/LIC_test.java
- src/main/CMV.java
> Revert "Lic2 issue 13"

- src/junit/LIC_test.java
- src/main/CMV.java
New feature: LIC6 calculation
Added relevant tests which are all passing✅
> feat: Implemented LIC6 #20

- src/main/CMV.java
PR #58 and more specifically commit c9c08d5 messed the tests up, this fixes that
> fix the tests, closes #70

- src/junit/LIC_test.java
- src/main/CMV.java
Should be correct now with comments on all three tests and comments on lic2_calculate().
> Fix: Reopen and solved after revert of issue #13 close #13

- src/junit/LIC_test.java
- src/main/CMV.java
Get compile errors with accessing fields through parameters, but worked previously and it's been used elsewhere in code so it should be fine.
> Feature: Implemented lic12 /issue #10

- src/junit/LIC_test.java
- src/main/CMV.java
I haven't been able to test the tests since it seems to be broken atm.
> Feature: Lic14 Function & 3 test  passes /Issue #8

- src/junit/LIC_test.java
Also made minor adjustment to comment to look nicer.
> Fix: Removed duplicate G_PTS init close #87

- src/junit/LIC_test.java
- src/main/CMV.java
> feat: implement LIC13 including tests #9

- src/junit/Helper_Function_Test.java
- src/main/CMV.java
- src/main/Helper_Functions.java
Test passes for quadEvaluations() and lic4 still works and passes all of its tests.
> Fix/feat: Moved quadEvaluation() to helper + added test closes #95

- src/junit/Decide_Test.java
- src/main/Main.java
- src/main/Parameters.java
Creates the `decide` function in `Main.java`. Two tests were added which checks a launch and a no launch configuration.
> Decide function creation closes #42

- src/junit/Decide_Test.java
- src/junit/Helper_Function_Test.java
- src/junit/LIC_test.java
- src/main/CMV.java
- src/main/Helper_Functions.java
- src/main/Parameters.java
All test still passes including Decide_Test but look trough properly or test it yourself before accepting.
> Fix: Switched datapoints from int to double closes #102

- README.md
let me know what you guys think of the paragraph "our way of working". It relates to the framework set out in Essence, [here on page 60](https://www.omg.org/spec/Essence/1.2/PDF)
I think I covered the points. The assignment does say to do it in one paragraph, which is one of those impossible sounding tasks... Should I try condense to one paragraph? Or is it not a super strict requirement do you think?
> our way of working paragraph Issue/64
